# Generated by Django 4.0.1 on 2022-03-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliedUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=20)),
                ('org', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=40)),
                ('qualification', models.CharField(max_length=40)),
                ('expertise', models.CharField(max_length=100)),
            ],
        ),
    ]
