# Generated by Django 4.0.1 on 2022-03-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('op1', models.CharField(max_length=25)),
                ('op2', models.CharField(max_length=25)),
                ('op3', models.CharField(max_length=25)),
                ('op4', models.CharField(max_length=25)),
                ('answer', models.CharField(max_length=25)),
                ('tags', models.CharField(max_length=50)),
                ('difficulty', models.IntegerField()),
                ('isVerified', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
